name: hrms
description: A new Flutter project.


publish_to: 'none'

version: 2.2.1+23

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_lints: ^1.0.4
  flutter_dotenv: ^5.0.2
  provider: ^6.0.2
  rxdart: ^0.27.3
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.12
  google_fonts: ^2.2.0
  cached_network_image: ^3.2.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  flutter_bloc: ^8.0.1
  nb_utils: ^4.4.11
  equatable: ^2.0.3
  flutter_svg: ^1.0.3
  dio: ^4.0.4
  shimmer: ^2.0.0
  multi_select_flutter: ^4.0.0
  flutter_slidable: ^1.2.0
  url_launcher: ^6.0.20
  intl: ^0.17.0
  timelines: ^0.1.0
  image_picker: ^0.8.4+4
  badges: ^2.0.2
  syncfusion_flutter_charts: ^19.4.55
  flutter_native_splash: ^2.1.0
  firebase_core: ^1.4.0
  in_app_update: ^3.0.0
  new_version: ^0.3.0
  easy_localization: ^3.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  build_runner: ^2.1.7


flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - google_fonts/
    - assets/images/
    - assets/icons/
    - .env