// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAotmQHmuXGL9N_9W4donRdBWNGUaNDt5w',
    appId: '1:843392102560:android:faa11fcc18df76c432d9c5',
    messagingSenderId: '843392102560',
    projectId: 'hrms-59f53',
    storageBucket: 'hrms-59f53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwF0HGOI3wolfm9AZfZ-dEuJtAFu6C1sc',
    appId: '1:843392102560:ios:9c21fcc6a1e7560732d9c5',
    messagingSenderId: '843392102560',
    projectId: 'hrms-59f53',
    storageBucket: 'hrms-59f53.appspot.com',
    iosClientId: '843392102560-9ob3rrjt2823vk4octhj5557h7lab2c2.apps.googleusercontent.com',
    iosBundleId: 'com.ishonch.hrms',
  );
}
