// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCROd2WHJOM4-v8vJ97M1B_D-TpVlC2NHQ',
    appId: '1:843392102560:web:8cfae64c2c64473132d9c5',
    messagingSenderId: '843392102560',
    projectId: 'hrms-59f53',
    authDomain: 'hrms-59f53.firebaseapp.com',
    storageBucket: 'hrms-59f53.appspot.com',
    measurementId: 'G-H8T44TD3RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAotmQHmuXGL9N_9W4donRdBWNGUaNDt5w',
    appId: '1:843392102560:android:4f0eb4501d0e2a1d32d9c5',
    messagingSenderId: '843392102560',
    projectId: 'hrms-59f53',
    storageBucket: 'hrms-59f53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwF0HGOI3wolfm9AZfZ-dEuJtAFu6C1sc',
    appId: '1:843392102560:ios:9c21fcc6a1e7560732d9c5',
    messagingSenderId: '843392102560',
    projectId: 'hrms-59f53',
    storageBucket: 'hrms-59f53.appspot.com',
    iosClientId: '843392102560-9ob3rrjt2823vk4octhj5557h7lab2c2.apps.googleusercontent.com',
    iosBundleId: 'com.ishonch.hrms',
  );
}
